[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
todo_list_dapp = "5reFTz45EsYQFjXfbmrQ9kU94ceoqkFDim36hR1rkfZK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jorshimayor/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
